# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rift < Formula
  desc "Rift — ephemeral developer workspaces CLI"
  homepage "https://github.com/fixed-labs/oss"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.3/rift_0.1.3_darwin_amd64.tar.gz"
      sha256 "4e0c5ad66976448ed1b58c7e0efd36df57822aead3ea80b8b70995cd41c6c2f1"

      define_method(:install) do
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.3/rift_0.1.3_darwin_arm64.tar.gz"
      sha256 "9c00d5fc34cfecc4211bec2c7a441c173203b91b9891ceb116e2bc0d0ec5ccce"

      define_method(:install) do
        bin.install "rift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.3/rift_0.1.3_linux_amd64.tar.gz"
      sha256 "85c26ad5ecc6f5f46a9611d05f38c356acd7554daa51b5e1649e7f5ba7557fbe"
      define_method(:install) do
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.3/rift_0.1.3_linux_arm64.tar.gz"
      sha256 "5c7b62f6ff174da0ee40642c1f880a1ce54d9c174543f7b494d3d2393f894bbe"
      define_method(:install) do
        bin.install "rift"
      end
    end
  end

  test do
    system "#{bin}/rift", "version"
  end
end
