# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rift < Formula
  desc "Rift — ephemeral developer workspaces CLI"
  homepage "https://github.com/fixed-labs/oss"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.1/rift_0.1.1_darwin_amd64.tar.gz"
      sha256 "8cd6c0b3de90fb631c902dfa8e3783e43dfabf81dd12ddbad3573886b05532af"

      define_method(:install) do
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.1/rift_0.1.1_darwin_arm64.tar.gz"
      sha256 "c83047c19e2cbb6dd79746f57b88e7fd93ae9040f38e093492b01d2d9190b66e"

      define_method(:install) do
        bin.install "rift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.1/rift_0.1.1_linux_amd64.tar.gz"
      sha256 "811cfe79c93cc1af119f3ffebbb3b8725a40d4f73ea9c3ef9030d2073e116c7c"
      define_method(:install) do
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fixed-labs/oss/releases/download/v0.1.1/rift_0.1.1_linux_arm64.tar.gz"
      sha256 "3d9e3ae4cbb52b79a0d032f9304c45e700744634c00b6e3400f6774129e75fc4"
      define_method(:install) do
        bin.install "rift"
      end
    end
  end

  test do
    system "#{bin}/rift", "version"
  end
end
